// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Equalize (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_dout,
        p_src_rows_V_empty_n,
        p_src_rows_V_read,
        p_src_cols_V_dout,
        p_src_cols_V_empty_n,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp0_stage0 = 10'd8;
parameter    ap_ST_fsm_state7 = 10'd16;
parameter    ap_ST_fsm_state8 = 10'd32;
parameter    ap_ST_fsm_state9 = 10'd64;
parameter    ap_ST_fsm_pp2_stage0 = 10'd128;
parameter    ap_ST_fsm_pp2_stage1 = 10'd256;
parameter    ap_ST_fsm_state25 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_dout;
input   p_src_rows_V_empty_n;
output   p_src_rows_V_read;
input  [31:0] p_src_cols_V_dout;
input   p_src_cols_V_empty_n;
output   p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_rows_V_read;
reg p_src_cols_V_read;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] hls_lut_V_address0;
reg    hls_lut_V_ce0;
reg    hls_lut_V_we0;
reg   [7:0] hls_lut_V_d0;
wire   [7:0] hls_lut_V_q0;
reg    p_src_rows_V_blk_n;
reg    p_src_cols_V_blk_n;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_37_i_reg_1907;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] tmp_37_i_reg_1907_pp0_iter1_reg;
reg   [30:0] j_i_reg_409;
reg   [8:0] i6_i_reg_431;
reg   [8:0] i6_i_reg_431_pp2_iter1_reg;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state10_pp2_stage0_iter0;
wire    ap_block_state12_pp2_stage0_iter1;
wire    ap_block_state14_pp2_stage0_iter2;
wire    ap_block_state16_pp2_stage0_iter3;
wire    ap_block_state18_pp2_stage0_iter4;
wire    ap_block_state20_pp2_stage0_iter5;
wire    ap_block_state22_pp2_stage0_iter6;
wire    ap_block_state24_pp2_stage0_iter7;
wire    ap_block_pp2_stage0_11001;
reg   [8:0] i6_i_reg_431_pp2_iter2_reg;
reg   [8:0] i6_i_reg_431_pp2_iter3_reg;
reg  signed [31:0] rows_reg_1810;
reg    ap_block_state1;
reg  signed [31:0] cols_reg_1816;
wire   [8:0] i_fu_479_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_36_i_fu_534_p2;
wire    ap_CS_fsm_state3;
wire   [30:0] i_1_fu_539_p2;
reg   [30:0] i_1_reg_1902;
wire   [0:0] tmp_37_i_fu_549_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [30:0] j_fu_554_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_23_reg_1916;
wire   [1:0] m_fu_953_p2;
wire    ap_CS_fsm_state8;
wire  signed [32:0] lhs_V_fu_991_p1;
reg  signed [32:0] lhs_V_reg_1964;
wire    ap_CS_fsm_state9;
wire   [0:0] exitcond_i_fu_1010_p2;
reg   [0:0] exitcond_i_reg_1969;
wire   [8:0] i_2_fu_1016_p2;
reg   [8:0] i_2_reg_1973;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] flag5_i_load_load_fu_1022_p1;
reg   [0:0] flag5_i_load_reg_1978;
reg   [0:0] flag5_i_load_reg_1978_pp2_iter1_reg;
reg   [0:0] flag5_i_load_reg_1978_pp2_iter2_reg;
reg   [0:0] flag5_i_load_reg_1978_pp2_iter3_reg;
reg   [0:0] flag5_i_load_reg_1978_pp2_iter4_reg;
reg   [0:0] flag5_i_load_reg_1978_pp2_iter5_reg;
reg   [0:0] flag5_i_load_reg_1978_pp2_iter6_reg;
wire   [63:0] tmp_44_i_fu_1025_p1;
reg   [63:0] tmp_44_i_reg_1982;
wire   [0:0] tmp_45_i_fu_1030_p2;
reg   [0:0] tmp_45_i_reg_1992;
wire    ap_CS_fsm_pp2_stage1;
wire    ap_block_state11_pp2_stage1_iter0;
wire    ap_block_state13_pp2_stage1_iter1;
wire    ap_block_state15_pp2_stage1_iter2;
wire    ap_block_state17_pp2_stage1_iter3;
wire    ap_block_state19_pp2_stage1_iter4;
wire    ap_block_state21_pp2_stage1_iter5;
wire    ap_block_state23_pp2_stage1_iter6;
wire    ap_block_pp2_stage1_11001;
reg   [0:0] tmp_45_i_reg_1992_pp2_iter1_reg;
reg   [0:0] tmp_45_i_reg_1992_pp2_iter2_reg;
reg   [0:0] tmp_45_i_reg_1992_pp2_iter3_reg;
reg   [0:0] tmp_45_i_reg_1992_pp2_iter4_reg;
reg   [0:0] tmp_45_i_reg_1992_pp2_iter5_reg;
reg   [0:0] tmp_45_i_reg_1992_pp2_iter6_reg;
wire   [32:0] ret_V_1_fu_1040_p2;
reg   [32:0] ret_V_1_reg_1996;
wire   [31:0] grp_fu_455_p1;
reg   [31:0] tmp_49_i_reg_2006;
wire   [63:0] tmp_46_i_fu_1054_p1;
reg   [63:0] tmp_46_i_reg_2011;
reg   [63:0] tmp_46_i_reg_2011_pp2_iter4_reg;
reg   [63:0] tmp_46_i_reg_2011_pp2_iter5_reg;
reg   [63:0] tmp_46_i_reg_2011_pp2_iter6_reg;
wire   [19:0] hist_out_V_q1;
reg   [19:0] hist_out_V_load_1_reg_2021;
reg    ap_enable_reg_pp2_iter4;
wire   [31:0] grp_fu_452_p1;
reg   [31:0] tmp_47_i_reg_2031;
wire   [31:0] grp_fu_447_p2;
reg   [31:0] scale_reg_2036;
wire   [31:0] v_assign_fu_443_p2;
reg   [31:0] v_assign_reg_2041;
wire   [0:0] tmp_i_i_i_i_fu_1102_p2;
reg   [0:0] tmp_i_i_i_i_reg_2047;
wire   [0:0] tmp_i_i_i_i_79_fu_1108_p2;
reg   [0:0] tmp_i_i_i_i_79_reg_2053;
wire   [0:0] p_Result_7_fu_1122_p3;
reg   [0:0] p_Result_7_reg_2059;
wire   [53:0] p_Val2_s_fu_1166_p3;
reg   [53:0] p_Val2_s_reg_2067;
wire   [0:0] tmp_3_i_fu_1174_p2;
reg   [0:0] tmp_3_i_reg_2073;
wire   [0:0] tmp_5_i_fu_1186_p2;
reg   [0:0] tmp_5_i_reg_2079;
wire  signed [11:0] F2_2_fu_1198_p3;
reg  signed [11:0] F2_2_reg_2085;
wire   [0:0] tmp_7_i_fu_1210_p2;
reg   [0:0] tmp_7_i_reg_2090;
wire   [7:0] tmp_13_fu_1216_p1;
reg   [7:0] tmp_13_reg_2097;
wire   [0:0] icmp1_fu_1236_p2;
reg   [0:0] icmp1_reg_2103;
wire   [7:0] p_Val2_3_fu_1272_p3;
reg   [7:0] p_Val2_3_reg_2109;
wire   [0:0] tmp_17_i_fu_1280_p2;
reg   [0:0] tmp_17_i_reg_2114;
wire   [11:0] tmp_18_i_fu_1286_p2;
reg   [11:0] tmp_18_i_reg_2119;
reg   [0:0] p_Result_9_reg_2124;
wire   [0:0] tmp_21_i_fu_1320_p2;
reg   [0:0] tmp_21_i_reg_2130;
wire   [0:0] rev1_fu_1334_p2;
reg   [0:0] rev1_reg_2136;
wire   [0:0] Range1_all_ones_1_fu_1360_p2;
reg   [0:0] Range1_all_ones_1_reg_2143;
reg   [0:0] tmp_22_reg_2150;
wire   [0:0] tmp_26_i_fu_1374_p2;
reg   [0:0] tmp_26_i_reg_2155;
wire   [53:0] tmp_27_i_fu_1380_p1;
reg   [53:0] tmp_27_i_reg_2161;
wire   [53:0] Range2_V_1_fu_1384_p2;
reg   [53:0] Range2_V_1_reg_2166;
wire   [0:0] sel_tmp34_i_fu_1408_p2;
reg   [0:0] sel_tmp34_i_reg_2172;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state10;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage1_subdone;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp2_iter3;
reg    ap_enable_reg_pp2_iter5;
reg    ap_enable_reg_pp2_iter6;
reg    ap_enable_reg_pp2_iter7;
reg   [7:0] hist_out_V_address0;
reg    hist_out_V_ce0;
reg    hist_out_V_we0;
wire   [19:0] hist_out_V_q0;
reg   [7:0] hist_out_V_address1;
reg    hist_out_V_ce1;
reg    hist_out_V_we1;
reg   [19:0] hist_out_V_d1;
reg   [8:0] i1_i_reg_387;
wire   [0:0] exitcond3_i_fu_473_p2;
reg   [30:0] i2_i_reg_398;
wire    ap_CS_fsm_state7;
reg   [1:0] col_assign_reg_420;
wire   [0:0] exitcond4_i_fu_947_p2;
reg   [8:0] ap_phi_mux_i6_i_phi_fu_435_p4;
wire    ap_block_pp2_stage0;
wire   [63:0] tmp_i_fu_485_p1;
wire   [63:0] tmp_39_i_fu_560_p1;
wire   [63:0] tmp_55_i_fu_892_p1;
wire   [63:0] tmp_38_i_fu_973_p1;
wire    ap_block_pp2_stage1;
reg    ap_block_pp0_stage0_01001;
reg   [19:0] p_0351_i_fu_226;
wire   [19:0] p_0351_2_be_2_i_fu_791_p3;
reg   [7:0] p_0354_i_fu_230;
wire   [7:0] p_0354_2_be_2_i_fu_783_p3;
reg   [7:0] addr_win_val_0_V_2_fu_234;
reg   [7:0] addr_win_val_0_V_1_fu_238;
wire   [7:0] addr_win_val_V_0_0_2_fu_884_p3;
reg   [7:0] addr_win_val_0_V_3_fu_242;
reg   [7:0] addr_last_V_fu_246;
reg   [19:0] hist_win_val_0_V_1_1_fu_250;
wire   [19:0] hist_win_val_0_V_1_fu_775_p3;
reg   [19:0] hist_win_val_V_0_0_i_fu_254;
wire   [19:0] hist_win_val_V_0_0_2_fu_869_p3;
reg   [19:0] hist_win_val_0_V_2_1_fu_258;
wire   [19:0] hist_win_val_0_V_2_fu_738_p3;
reg   [19:0] hist_win_val_0_V_3_1_fu_262;
wire   [19:0] hist_win_val_0_V_3_fu_702_p3;
reg   [0:0] flag5_i_fu_266;
reg   [31:0] i_op_assign_fu_270;
reg   [19:0] sum_V_1_fu_274;
wire   [19:0] sum_V_fu_1062_p2;
wire   [19:0] hist_win_val_V_load_s_fu_978_p3;
wire   [7:0] val_V_fu_1801_p3;
wire    ap_CS_fsm_state25;
wire   [31:0] grp_fu_452_p0;
wire  signed [63:0] grp_fu_455_p0;
wire   [31:0] i2_cast_i_fu_530_p1;
wire   [31:0] j_cast_i_fu_545_p1;
wire   [0:0] tmp_59_i_fu_584_p2;
wire   [0:0] tmp_59_3_i_fu_599_p2;
wire   [0:0] tmp_3_fu_612_p2;
wire   [2:0] p_i_cast_fu_604_p3;
wire   [0:0] tmp_59_1_i_fu_589_p2;
wire   [0:0] sel_tmp1_fu_626_p2;
wire   [0:0] sel_tmp6_demorgan_fu_638_p2;
wire   [0:0] tmp_59_2_i_fu_594_p2;
wire   [0:0] sel_tmp6_fu_644_p2;
wire   [0:0] sel_tmp7_fu_650_p2;
wire   [0:0] sel_tmp2_fu_632_p2;
wire   [0:0] tmp_4_fu_664_p2;
wire   [2:0] sel_tmp3_cast_fu_656_p3;
wire   [2:0] sel_tmp_fu_618_p3;
wire   [2:0] p_3_i_fu_670_p3;
wire   [2:0] ret_V_fu_684_p2;
wire   [0:0] tmp_75_i_fu_690_p2;
wire   [19:0] hist_flag_V_i_fu_696_p2;
wire   [0:0] tmp_73_1_i_fu_726_p2;
wire   [19:0] hist_w_V_i_fu_732_p2;
wire   [7:0] p_0354_2_be_i_fu_710_p3;
wire   [19:0] p_0351_2_be_i_fu_718_p3;
wire   [0:0] tmp_75_2_i_fu_763_p2;
wire   [19:0] hist_flag_V_2_i_fu_769_p2;
wire   [7:0] addr_V_1_0354_2_be_s_fu_747_p3;
wire   [19:0] hist_w_V_169_0351_2_fu_755_p3;
wire   [1:0] tmp_6_fu_817_p4;
wire   [0:0] icmp_fu_827_p2;
wire   [0:0] tmp_51_i_fu_799_p2;
wire   [19:0] hist_win_val_0_V_0_fu_805_p2;
wire   [19:0] storemerge1_i_fu_841_p3;
wire   [0:0] tmp_53_i_fu_811_p2;
wire   [0:0] sel_tmp4_fu_857_p2;
wire   [0:0] sel_tmp5_fu_863_p2;
wire   [19:0] hist_last_V_fu_678_p2;
wire   [19:0] sel_tmp9_fu_849_p3;
wire   [7:0] storemerge_i_fu_833_p3;
wire   [7:0] sel_tmp8_fu_877_p3;
wire   [0:0] cond_i_fu_959_p2;
wire   [7:0] addr_win_val_V_load_s_fu_965_p3;
wire   [31:0] i_op_assign_3_fu_987_p2;
wire   [32:0] rhs_V_fu_1036_p1;
wire   [31:0] p_Val2_1_fu_1085_p1;
wire   [7:0] tmp_V_fu_1088_p4;
wire   [22:0] tmp_V_1_fu_1098_p1;
wire   [63:0] d_assign_fu_458_p1;
wire   [63:0] ireg_V_fu_1114_p1;
wire   [10:0] exp_tmp_V_fu_1130_p4;
wire   [51:0] tmp_11_fu_1144_p1;
wire   [52:0] tmp_i1_fu_1148_p3;
wire   [53:0] p_Result_8_fu_1156_p1;
wire   [53:0] man_V_1_fu_1160_p2;
wire   [62:0] tmp_8_fu_1118_p1;
wire   [11:0] tmp_1_i_fu_1140_p1;
wire   [11:0] F2_fu_1180_p2;
wire   [11:0] tmp_6_i_fu_1192_p2;
wire   [8:0] tmp_14_fu_1226_p4;
wire  signed [31:0] F2_2_cast_i_fu_1206_p1;
wire   [53:0] tmp_10_i_fu_1242_p1;
wire   [53:0] tmp_11_i_fu_1246_p2;
wire   [0:0] tmp_16_fu_1256_p3;
wire   [0:0] tmp_9_i_fu_1220_p2;
wire   [7:0] tmp_15_fu_1252_p1;
wire   [7:0] tmp_15_i_fu_1264_p3;
wire  signed [11:0] pos1_fu_1300_p2;
wire  signed [11:0] pos2_fu_1310_p2;
wire   [0:0] tmp_20_fu_1326_p3;
wire  signed [31:0] pos1_cast_i_fu_1306_p1;
wire   [53:0] tmp_23_i_fu_1340_p1;
wire   [53:0] tmp_24_i_fu_1344_p2;
wire   [0:0] lD_fu_1350_p1;
wire   [0:0] tmp6_fu_1354_p2;
wire  signed [31:0] pos2_cast_i_fu_1316_p1;
wire   [0:0] tmp_26_i_not_fu_1396_p2;
wire   [0:0] tmp_30_i_fu_1390_p2;
wire   [0:0] sel_tmp33_i_fu_1402_p2;
wire   [7:0] tmp_12_fu_1418_p1;
wire   [31:0] tmp_20_cast_i_fu_1426_p1;
wire   [0:0] p_Result_s_fu_1429_p3;
wire   [0:0] qb_fu_1436_p3;
wire   [7:0] tmp_19_i_fu_1442_p1;
wire   [7:0] p_Val2_4_fu_1446_p2;
wire   [0:0] tmp_18_fu_1451_p3;
wire   [0:0] sel_tmp1_i_fu_1471_p2;
wire   [0:0] sel_tmp2_i_fu_1476_p2;
wire   [0:0] sel_tmp3_i_fu_1481_p2;
wire   [7:0] sel_tmp_i_fu_1465_p3;
wire   [0:0] sel_tmp7_i_fu_1494_p2;
wire   [0:0] sel_tmp8_i_fu_1499_p2;
wire   [7:0] sel_tmp4_i_fu_1486_p3;
wire   [0:0] sel_tmp12_demorgan_i_fu_1513_p2;
wire   [0:0] sel_tmp12_i_fu_1517_p2;
wire   [0:0] sel_tmp13_i_fu_1523_p2;
wire   [7:0] tmp_16_i_fu_1421_p2;
wire   [7:0] sel_tmp9_i_fu_1505_p3;
wire   [0:0] tmp_4_not_i_fu_1536_p2;
wire   [0:0] not_sel_tmp28_i_fu_1541_p2;
wire   [0:0] rev_fu_1459_p2;
wire   [0:0] tmp5_fu_1547_p2;
wire   [7:0] p_Val2_5_fu_1528_p3;
wire   [0:0] rev2_fu_1567_p2;
wire   [53:0] r_V_fu_1577_p2;
wire   [0:0] or_cond173_i_i_i_fu_1572_p2;
wire   [0:0] Range2_all_ones_fu_1582_p2;
wire   [0:0] Range2_all_ones_1_i_s_fu_1587_p3;
wire   [0:0] tmp_28_i_fu_1604_p2;
wire   [0:0] Range1_all_zeros_fu_1609_p2;
wire   [0:0] Range1_all_zeros_1_fu_1620_p2;
wire   [0:0] or_cond175_i_i_i_fu_1595_p2;
wire   [0:0] Range1_all_ones_fu_1599_p2;
wire   [0:0] sel_tmp35_i_fu_1630_p3;
wire   [0:0] p_177_i_i_i_fu_1625_p2;
wire   [0:0] p_180_i_i_i_fu_1614_p2;
wire   [0:0] sel_tmp39_i_fu_1643_p3;
wire   [0:0] carry_1_i_i_i_fu_1553_p2;
wire   [0:0] Range1_all_ones_2_i_s_fu_1635_p3;
wire   [0:0] Range1_all_zeros_2_i_fu_1650_p3;
wire   [0:0] Range1_all_ones_2_i_fu_1666_p2;
wire   [0:0] p_Result_10_fu_1559_p3;
wire   [0:0] sel_tmp41_i_fu_1678_p2;
wire   [0:0] tmp7_fu_1683_p2;
wire   [0:0] sel_tmp47_i_fu_1694_p2;
wire   [0:0] tmp_31_i_fu_1672_p2;
wire   [0:0] sel_tmp46_i_fu_1689_p2;
wire   [0:0] tmp8_fu_1706_p2;
wire   [0:0] deleted_zeros_fu_1658_p3;
wire   [0:0] underflow_fu_1698_p3;
wire   [0:0] p_179_demorgan_i_i_i_fu_1711_p2;
wire   [0:0] underflow_not_i_fu_1717_p2;
wire   [0:0] p_179_demorgan_i_i_no_fu_1729_p2;
wire   [0:0] brmerge_i_i_not_i_fu_1723_p2;
wire   [0:0] sel_tmp50_i_demorgan_fu_1749_p2;
wire   [0:0] sel_tmp50_i_fu_1753_p2;
wire   [0:0] sel_tmp51_i_fu_1759_p2;
wire   [0:0] tmp_demorgan_i_fu_1414_p2;
wire   [0:0] tmp_9_fu_1764_p2;
wire   [0:0] tmp_5_fu_1770_p2;
wire   [0:0] sel_tmp55_demorgan_i_fu_1784_p2;
wire   [0:0] brmerge_i_fu_1735_p2;
wire   [0:0] sel_tmp55_i_fu_1789_p2;
wire   [0:0] sel_tmp56_i_fu_1795_p2;
wire   [7:0] p_Val2_11_0_i_i_mux_fu_1741_p3;
wire   [7:0] sel_tmp52_i_fu_1776_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_block_pp2;
reg    ap_enable_operation_83;
reg    ap_enable_state5_pp0_iter1_stage0;
reg    ap_enable_operation_134;
reg    ap_enable_state6_pp0_iter2_stage0;
reg    ap_enable_operation_149;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp2;
wire    ap_enable_pp2;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter4 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter5 = 1'b0;
#0 ap_enable_reg_pp2_iter6 = 1'b0;
#0 ap_enable_reg_pp2_iter7 = 1'b0;
end

Equalize_hls_lut_V #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_lut_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_lut_V_address0),
    .ce0(hls_lut_V_ce0),
    .we0(hls_lut_V_we0),
    .d0(hls_lut_V_d0),
    .q0(hls_lut_V_q0)
);

Equalize_hist_out_V #(
    .DataWidth( 20 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hist_out_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hist_out_V_address0),
    .ce0(hist_out_V_ce0),
    .we0(hist_out_V_we0),
    .d0(20'd0),
    .q0(hist_out_V_q0),
    .address1(hist_out_V_address1),
    .ce1(hist_out_V_ce1),
    .we1(hist_out_V_we1),
    .d1(hist_out_V_d1),
    .q1(hist_out_V_q1)
);

equalize_hist_fmueOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
equalize_hist_fmueOg_U37(
    .din0(tmp_47_i_reg_2031),
    .din1(i_op_assign_fu_270),
    .dout(v_assign_fu_443_p2)
);

equalize_hist_fdifYi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
equalize_hist_fdifYi_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1132396544),
    .din1(tmp_49_i_reg_2006),
    .ce(1'b1),
    .dout(grp_fu_447_p2)
);

equalize_hist_uitg8j #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
equalize_hist_uitg8j_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_452_p0),
    .ce(1'b1),
    .dout(grp_fu_452_p1)
);

equalize_hist_sithbi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
equalize_hist_sithbi_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_455_p0),
    .ce(1'b1),
    .dout(grp_fu_455_p1)
);

equalize_hist_fpeibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
equalize_hist_fpeibs_U41(
    .din0(v_assign_reg_2041),
    .dout(d_assign_fu_458_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state25)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_37_i_fu_549_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_36_i_fu_534_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((tmp_36_i_fu_534_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_condition_pp2_exit_iter0_state10))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            ap_enable_reg_pp2_iter6 <= ap_enable_reg_pp2_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter7 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1)))) begin
            ap_enable_reg_pp2_iter7 <= ap_enable_reg_pp2_iter6;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            ap_enable_reg_pp2_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        addr_last_V_fu_246 <= addr_win_val_0_V_3_fu_242;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        addr_last_V_fu_246 <= 8'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        addr_win_val_0_V_1_fu_238 <= addr_win_val_V_0_0_2_fu_884_p3;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        addr_win_val_0_V_1_fu_238 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        addr_win_val_0_V_2_fu_234 <= addr_win_val_0_V_1_fu_238;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        addr_win_val_0_V_2_fu_234 <= 8'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        addr_win_val_0_V_3_fu_242 <= addr_win_val_0_V_2_fu_234;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        addr_win_val_0_V_3_fu_242 <= 8'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_36_i_fu_534_p2 == 1'd0))) begin
        col_assign_reg_420 <= 2'd0;
    end else if (((exitcond4_i_fu_947_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        col_assign_reg_420 <= m_fu_953_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (tmp_45_i_fu_1030_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (flag5_i_load_reg_1978 == 1'd0) & (exitcond_i_reg_1969 == 1'd0))) begin
        flag5_i_fu_266 <= 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        flag5_i_fu_266 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        hist_win_val_0_V_1_1_fu_250 <= hist_win_val_0_V_1_fu_775_p3;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        hist_win_val_0_V_1_1_fu_250 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        hist_win_val_0_V_2_1_fu_258 <= hist_win_val_0_V_2_fu_738_p3;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        hist_win_val_0_V_2_1_fu_258 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        hist_win_val_0_V_3_1_fu_262 <= hist_win_val_0_V_3_fu_702_p3;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        hist_win_val_0_V_3_1_fu_262 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        hist_win_val_V_0_0_i_fu_254 <= hist_win_val_V_0_0_2_fu_869_p3;
    end else if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        hist_win_val_V_0_0_i_fu_254 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i1_i_reg_387 <= 9'd0;
    end else if (((exitcond3_i_fu_473_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_i_reg_387 <= i_fu_479_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i2_i_reg_398 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i2_i_reg_398 <= i_1_reg_1902;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (exitcond_i_reg_1969 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        i6_i_reg_431 <= i_2_reg_1973;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i6_i_reg_431 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (tmp_45_i_reg_1992_pp2_iter5_reg == 1'd0) & (flag5_i_load_reg_1978_pp2_iter6_reg == 1'd0) & (ap_enable_reg_pp2_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        i_op_assign_fu_270 <= scale_reg_2036;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_op_assign_fu_270 <= 32'd1065353216;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_fu_549_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_i_reg_409 <= j_fu_554_p2;
    end else if (((tmp_36_i_fu_534_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        j_i_reg_409 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & ((tmp_45_i_reg_1992_pp2_iter3_reg == 1'd1) | (flag5_i_load_reg_1978_pp2_iter4_reg == 1'd1)))) begin
        sum_V_1_fu_274 <= sum_V_fu_1062_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        sum_V_1_fu_274 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & ((tmp_45_i_reg_1992_pp2_iter5_reg == 1'd1) | (flag5_i_load_reg_1978_pp2_iter6_reg == 1'd1)))) begin
        F2_2_reg_2085 <= F2_2_fu_1198_p3;
        Range1_all_ones_1_reg_2143 <= Range1_all_ones_1_fu_1360_p2;
        Range2_V_1_reg_2166 <= Range2_V_1_fu_1384_p2;
        icmp1_reg_2103 <= icmp1_fu_1236_p2;
        p_Result_7_reg_2059 <= ireg_V_fu_1114_p1[32'd63];
        p_Result_9_reg_2124 <= p_Val2_3_fu_1272_p3[32'd7];
        p_Val2_3_reg_2109 <= p_Val2_3_fu_1272_p3;
        p_Val2_s_reg_2067 <= p_Val2_s_fu_1166_p3;
        rev1_reg_2136 <= rev1_fu_1334_p2;
        sel_tmp34_i_reg_2172 <= sel_tmp34_i_fu_1408_p2;
        tmp_13_reg_2097 <= tmp_13_fu_1216_p1;
        tmp_17_i_reg_2114 <= tmp_17_i_fu_1280_p2;
        tmp_18_i_reg_2119 <= tmp_18_i_fu_1286_p2;
        tmp_21_i_reg_2130 <= tmp_21_i_fu_1320_p2;
        tmp_22_reg_2150 <= pos2_fu_1310_p2[32'd11];
        tmp_26_i_reg_2155 <= tmp_26_i_fu_1374_p2;
        tmp_27_i_reg_2161[31 : 0] <= tmp_27_i_fu_1380_p1[31 : 0];
        tmp_3_i_reg_2073 <= tmp_3_i_fu_1174_p2;
        tmp_5_i_reg_2079 <= tmp_5_i_fu_1186_p2;
        tmp_7_i_reg_2090 <= tmp_7_i_fu_1210_p2;
        tmp_i_i_i_i_79_reg_2053 <= tmp_i_i_i_i_79_fu_1108_p2;
        tmp_i_i_i_i_reg_2047 <= tmp_i_i_i_i_fu_1102_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_reg_1816 <= p_src_cols_V_dout;
        rows_reg_1810 <= p_src_rows_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        exitcond_i_reg_1969 <= exitcond_i_fu_1010_p2;
        flag5_i_load_reg_1978_pp2_iter1_reg <= flag5_i_load_reg_1978;
        flag5_i_load_reg_1978_pp2_iter2_reg <= flag5_i_load_reg_1978_pp2_iter1_reg;
        flag5_i_load_reg_1978_pp2_iter3_reg <= flag5_i_load_reg_1978_pp2_iter2_reg;
        flag5_i_load_reg_1978_pp2_iter4_reg <= flag5_i_load_reg_1978_pp2_iter3_reg;
        flag5_i_load_reg_1978_pp2_iter5_reg <= flag5_i_load_reg_1978_pp2_iter4_reg;
        flag5_i_load_reg_1978_pp2_iter6_reg <= flag5_i_load_reg_1978_pp2_iter5_reg;
        i6_i_reg_431_pp2_iter1_reg <= i6_i_reg_431;
        i6_i_reg_431_pp2_iter2_reg <= i6_i_reg_431_pp2_iter1_reg;
        i6_i_reg_431_pp2_iter3_reg <= i6_i_reg_431_pp2_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_i_fu_1010_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        flag5_i_load_reg_1978 <= flag5_i_fu_266;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & ((tmp_45_i_reg_1992_pp2_iter3_reg == 1'd1) | (flag5_i_load_reg_1978_pp2_iter3_reg == 1'd1)))) begin
        hist_out_V_load_1_reg_2021 <= hist_out_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_1_reg_1902 <= i_1_fu_539_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        i_2_reg_1973 <= i_2_fu_1016_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        lhs_V_reg_1964 <= lhs_V_fu_991_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0351_i_fu_226 <= p_0351_2_be_2_i_fu_791_p3;
        p_0354_i_fu_230 <= p_0354_2_be_2_i_fu_783_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (tmp_45_i_fu_1030_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (flag5_i_load_reg_1978 == 1'd0) & (exitcond_i_reg_1969 == 1'd0))) begin
        ret_V_1_reg_1996 <= ret_V_1_fu_1040_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_45_i_reg_1992_pp2_iter5_reg == 1'd0) & (flag5_i_load_reg_1978_pp2_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        scale_reg_2036 <= grp_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_i_reg_1907 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_23_reg_1916 <= p_src_data_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_37_i_reg_1907 <= tmp_37_i_fu_549_p2;
        tmp_37_i_reg_1907_pp0_iter1_reg <= tmp_37_i_reg_1907;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (flag5_i_load_load_fu_1022_p1 == 1'd0) & (exitcond_i_fu_1010_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_44_i_reg_1982[8 : 0] <= tmp_44_i_fu_1025_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & (flag5_i_load_reg_1978 == 1'd0) & (exitcond_i_reg_1969 == 1'd0))) begin
        tmp_45_i_reg_1992 <= tmp_45_i_fu_1030_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        tmp_45_i_reg_1992_pp2_iter1_reg <= tmp_45_i_reg_1992;
        tmp_45_i_reg_1992_pp2_iter2_reg <= tmp_45_i_reg_1992_pp2_iter1_reg;
        tmp_45_i_reg_1992_pp2_iter3_reg <= tmp_45_i_reg_1992_pp2_iter2_reg;
        tmp_45_i_reg_1992_pp2_iter4_reg <= tmp_45_i_reg_1992_pp2_iter3_reg;
        tmp_45_i_reg_1992_pp2_iter5_reg <= tmp_45_i_reg_1992_pp2_iter4_reg;
        tmp_45_i_reg_1992_pp2_iter6_reg <= tmp_45_i_reg_1992_pp2_iter5_reg;
        tmp_46_i_reg_2011_pp2_iter4_reg[8 : 0] <= tmp_46_i_reg_2011[8 : 0];
        tmp_46_i_reg_2011_pp2_iter5_reg[8 : 0] <= tmp_46_i_reg_2011_pp2_iter4_reg[8 : 0];
        tmp_46_i_reg_2011_pp2_iter6_reg[8 : 0] <= tmp_46_i_reg_2011_pp2_iter5_reg[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & ((tmp_45_i_reg_1992_pp2_iter2_reg == 1'd1) | (flag5_i_load_reg_1978_pp2_iter3_reg == 1'd1)))) begin
        tmp_46_i_reg_2011[8 : 0] <= tmp_46_i_fu_1054_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & ((tmp_45_i_reg_1992_pp2_iter4_reg == 1'd1) | (flag5_i_load_reg_1978_pp2_iter5_reg == 1'd1)))) begin
        tmp_47_i_reg_2031 <= grp_fu_452_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_45_i_reg_1992_pp2_iter1_reg == 1'd0) & (flag5_i_load_reg_1978_pp2_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_49_i_reg_2006 <= grp_fu_455_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & ((tmp_45_i_reg_1992_pp2_iter5_reg == 1'd1) | (flag5_i_load_reg_1978_pp2_iter5_reg == 1'd1)))) begin
        v_assign_reg_2041 <= v_assign_fu_443_p2;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_1010_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state10 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state10 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter7 == 1'b0) & (ap_enable_reg_pp2_iter6 == 1'b0) & (ap_enable_reg_pp2_iter5 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter4 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (exitcond_i_reg_1969 == 1'd0))) begin
        ap_phi_mux_i6_i_phi_fu_435_p4 = i_2_reg_1973;
    end else begin
        ap_phi_mux_i6_i_phi_fu_435_p4 = i6_i_reg_431;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        hist_out_V_address0 = tmp_44_i_fu_1025_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist_out_V_address0 = tmp_39_i_fu_560_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_out_V_address0 = tmp_i_fu_485_p1;
    end else begin
        hist_out_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        hist_out_V_address1 = tmp_46_i_fu_1054_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_out_V_address1 = tmp_38_i_fu_973_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        hist_out_V_address1 = tmp_55_i_fu_892_p1;
    end else begin
        hist_out_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        hist_out_V_ce0 = 1'b1;
    end else begin
        hist_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)))) begin
        hist_out_V_ce1 = 1'b1;
    end else begin
        hist_out_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_out_V_d1 = hist_win_val_V_load_s_fu_978_p3;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        hist_out_V_d1 = hist_win_val_0_V_2_fu_738_p3;
    end else begin
        hist_out_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((exitcond3_i_fu_473_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hist_out_V_we0 = 1'b1;
    end else begin
        hist_out_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond4_i_fu_947_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        hist_out_V_we1 = 1'b1;
    end else begin
        hist_out_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        hls_lut_V_address0 = 8'd0;
    end else if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter7 == 1'b1))) begin
        hls_lut_V_address0 = tmp_46_i_reg_2011_pp2_iter6_reg;
    end else if (((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        hls_lut_V_address0 = tmp_44_i_reg_1982;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hls_lut_V_address0 = tmp_39_i_fu_560_p1;
    end else begin
        hls_lut_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter7 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
        hls_lut_V_ce0 = 1'b1;
    end else begin
        hls_lut_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter7 == 1'b1))) begin
        hls_lut_V_d0 = val_V_fu_1801_p3;
    end else if (((1'b1 == ap_CS_fsm_state25) | ((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
        hls_lut_V_d0 = 8'd0;
    end else begin
        hls_lut_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter7 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & ((tmp_45_i_reg_1992_pp2_iter6_reg == 1'd1) | (flag5_i_load_reg_1978_pp2_iter6_reg == 1'd1))) | ((1'b0 == ap_block_pp2_stage1_11001) & (tmp_45_i_fu_1030_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (flag5_i_load_reg_1978 == 1'd0) & (exitcond_i_reg_1969 == 1'd0)))) begin
        hls_lut_V_we0 = 1'b1;
    end else begin
        hls_lut_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_V_blk_n = p_src_cols_V_empty_n;
    end else begin
        p_src_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_V_read = 1'b1;
    end else begin
        p_src_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_37_i_reg_1907 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_37_i_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_V_blk_n = p_src_rows_V_empty_n;
    end else begin
        p_src_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_V_read = 1'b1;
    end else begin
        p_src_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond3_i_fu_473_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (tmp_36_i_fu_534_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state8 : begin
            if (((exitcond4_i_fu_947_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((exitcond_i_fu_1010_p2 == 1'd1) & (ap_enable_reg_pp2_iter1 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1)) & ~((ap_enable_reg_pp2_iter6 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter7 == 1'b1)) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else if ((((ap_enable_reg_pp2_iter6 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter7 == 1'b1)) | ((exitcond_i_fu_1010_p2 == 1'd1) & (ap_enable_reg_pp2_iter1 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_2_cast_i_fu_1206_p1 = F2_2_fu_1198_p3;

assign F2_2_fu_1198_p3 = ((tmp_5_i_fu_1186_p2[0:0] === 1'b1) ? F2_fu_1180_p2 : tmp_6_i_fu_1192_p2);

assign F2_fu_1180_p2 = (12'd1075 - tmp_1_i_fu_1140_p1);

assign Range1_all_ones_1_fu_1360_p2 = (tmp_21_i_fu_1320_p2 & tmp6_fu_1354_p2);

assign Range1_all_ones_2_i_fu_1666_p2 = (carry_1_i_i_i_fu_1553_p2 & Range1_all_ones_2_i_s_fu_1635_p3);

assign Range1_all_ones_2_i_s_fu_1635_p3 = ((or_cond175_i_i_i_fu_1595_p2[0:0] === 1'b1) ? Range1_all_ones_fu_1599_p2 : sel_tmp35_i_fu_1630_p3);

assign Range1_all_ones_fu_1599_p2 = (Range2_all_ones_1_i_s_fu_1587_p3 & Range1_all_ones_1_reg_2143);

assign Range1_all_zeros_1_fu_1620_p2 = ((p_Val2_s_reg_2067 == 54'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_2_i_fu_1650_p3 = ((or_cond175_i_i_i_fu_1595_p2[0:0] === 1'b1) ? p_180_i_i_i_fu_1614_p2 : sel_tmp39_i_fu_1643_p3);

assign Range1_all_zeros_fu_1609_p2 = (1'd1 ^ Range1_all_ones_1_reg_2143);

assign Range2_V_1_fu_1384_p2 = p_Val2_s_fu_1166_p3 >> tmp_27_i_fu_1380_p1;

assign Range2_all_ones_1_i_s_fu_1587_p3 = ((or_cond173_i_i_i_fu_1572_p2[0:0] === 1'b1) ? Range2_all_ones_fu_1582_p2 : rev2_fu_1567_p2);

assign Range2_all_ones_fu_1582_p2 = ((Range2_V_1_reg_2166 == r_V_fu_1577_p2) ? 1'b1 : 1'b0);

assign addr_V_1_0354_2_be_s_fu_747_p3 = ((tmp_73_1_i_fu_726_p2[0:0] === 1'b1) ? addr_win_val_0_V_2_fu_234 : p_0354_2_be_i_fu_710_p3);

assign addr_win_val_V_0_0_2_fu_884_p3 = ((sel_tmp5_fu_863_p2[0:0] === 1'b1) ? addr_last_V_fu_246 : sel_tmp8_fu_877_p3);

assign addr_win_val_V_load_s_fu_965_p3 = ((cond_i_fu_959_p2[0:0] === 1'b1) ? addr_win_val_0_V_1_fu_238 : addr_win_val_0_V_2_fu_234);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_37_i_reg_1907 == 1'd1) & (p_src_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_37_i_reg_1907 == 1'd1) & (p_src_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_37_i_reg_1907 == 1'd1) & (p_src_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp2 = (((1'b1 == ap_block_pp2_stage0_subdone) & (ap_ST_fsm_pp2_stage0 == ap_CS_fsm)) | ((1'b1 == ap_block_pp2_stage1_subdone) & (ap_ST_fsm_pp2_stage1 == ap_CS_fsm)));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp2_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp2_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp2_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp2_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp2_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp2_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp2_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp2_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp2_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp2_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp2_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp2_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((tmp_37_i_reg_1907 == 1'd1) & (p_src_data_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = ((tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_enable_operation_134 = (tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1);
end

always @ (*) begin
    ap_enable_operation_149 = (tmp_37_i_reg_1907_pp0_iter1_reg == 1'd1);
end

always @ (*) begin
    ap_enable_operation_83 = (tmp_37_i_reg_1907 == 1'd1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state6_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign brmerge_i_fu_1735_p2 = (underflow_not_i_fu_1717_p2 | p_179_demorgan_i_i_no_fu_1729_p2);

assign brmerge_i_i_not_i_fu_1723_p2 = (underflow_not_i_fu_1717_p2 & p_179_demorgan_i_i_i_fu_1711_p2);

assign carry_1_i_i_i_fu_1553_p2 = (tmp5_fu_1547_p2 & sel_tmp3_i_fu_1481_p2);

assign cond_i_fu_959_p2 = ((col_assign_reg_420 == 2'd0) ? 1'b1 : 1'b0);

assign deleted_zeros_fu_1658_p3 = ((carry_1_i_i_i_fu_1553_p2[0:0] === 1'b1) ? Range1_all_ones_2_i_s_fu_1635_p3 : Range1_all_zeros_2_i_fu_1650_p3);

assign exitcond3_i_fu_473_p2 = ((i1_i_reg_387 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond4_i_fu_947_p2 = ((col_assign_reg_420 == 2'd2) ? 1'b1 : 1'b0);

assign exitcond_i_fu_1010_p2 = ((ap_phi_mux_i6_i_phi_fu_435_p4 == 9'd256) ? 1'b1 : 1'b0);

assign exp_tmp_V_fu_1130_p4 = {{ireg_V_fu_1114_p1[62:52]}};

assign flag5_i_load_load_fu_1022_p1 = flag5_i_fu_266;

assign grp_fu_452_p0 = sum_V_fu_1062_p2;

assign grp_fu_455_p0 = $signed(ret_V_1_reg_1996);

assign hist_flag_V_2_i_fu_769_p2 = (hist_win_val_V_0_0_i_fu_254 + 20'd1);

assign hist_flag_V_i_fu_696_p2 = (hist_win_val_0_V_2_1_fu_258 + 20'd1);

assign hist_last_V_fu_678_p2 = (hist_win_val_0_V_3_1_fu_262 + 20'd1);

assign hist_w_V_169_0351_2_fu_755_p3 = ((tmp_73_1_i_fu_726_p2[0:0] === 1'b1) ? hist_w_V_i_fu_732_p2 : p_0351_2_be_i_fu_718_p3);

assign hist_w_V_i_fu_732_p2 = (hist_win_val_0_V_1_1_fu_250 + 20'd1);

assign hist_win_val_0_V_0_fu_805_p2 = (hist_out_V_q0 + 20'd1);

assign hist_win_val_0_V_1_fu_775_p3 = ((tmp_75_2_i_fu_763_p2[0:0] === 1'b1) ? hist_flag_V_2_i_fu_769_p2 : hist_win_val_V_0_0_i_fu_254);

assign hist_win_val_0_V_2_fu_738_p3 = ((tmp_73_1_i_fu_726_p2[0:0] === 1'b1) ? hist_w_V_i_fu_732_p2 : hist_win_val_0_V_1_1_fu_250);

assign hist_win_val_0_V_3_fu_702_p3 = ((tmp_75_i_fu_690_p2[0:0] === 1'b1) ? hist_flag_V_i_fu_696_p2 : hist_win_val_0_V_2_1_fu_258);

assign hist_win_val_V_0_0_2_fu_869_p3 = ((sel_tmp5_fu_863_p2[0:0] === 1'b1) ? hist_last_V_fu_678_p2 : sel_tmp9_fu_849_p3);

assign hist_win_val_V_load_s_fu_978_p3 = ((cond_i_fu_959_p2[0:0] === 1'b1) ? hist_win_val_V_0_0_i_fu_254 : hist_win_val_0_V_1_1_fu_250);

assign i2_cast_i_fu_530_p1 = i2_i_reg_398;

assign i_1_fu_539_p2 = (i2_i_reg_398 + 31'd1);

assign i_2_fu_1016_p2 = (ap_phi_mux_i6_i_phi_fu_435_p4 + 9'd1);

assign i_fu_479_p2 = (i1_i_reg_387 + 9'd1);

assign i_op_assign_3_fu_987_p2 = ($signed(rows_reg_1810) * $signed(cols_reg_1816));

assign icmp1_fu_1236_p2 = ((tmp_14_fu_1226_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_fu_827_p2 = ((tmp_6_fu_817_p4 != 2'd0) ? 1'b1 : 1'b0);

assign ireg_V_fu_1114_p1 = d_assign_fu_458_p1;

assign j_cast_i_fu_545_p1 = j_i_reg_409;

assign j_fu_554_p2 = (j_i_reg_409 + 31'd1);

assign lD_fu_1350_p1 = tmp_24_i_fu_1344_p2[0:0];

assign lhs_V_fu_991_p1 = $signed(i_op_assign_3_fu_987_p2);

assign m_fu_953_p2 = (col_assign_reg_420 + 2'd1);

assign man_V_1_fu_1160_p2 = (54'd0 - p_Result_8_fu_1156_p1);

assign not_sel_tmp28_i_fu_1541_p2 = (tmp_4_not_i_fu_1536_p2 | sel_tmp12_demorgan_i_fu_1513_p2);

assign or_cond173_i_i_i_fu_1572_p2 = (tmp_26_i_reg_2155 & rev2_fu_1567_p2);

assign or_cond175_i_i_i_fu_1595_p2 = (tmp_26_i_reg_2155 & rev1_reg_2136);

assign p_0351_2_be_2_i_fu_791_p3 = ((tmp_75_2_i_fu_763_p2[0:0] === 1'b1) ? hist_flag_V_2_i_fu_769_p2 : hist_w_V_169_0351_2_fu_755_p3);

assign p_0351_2_be_i_fu_718_p3 = ((tmp_75_i_fu_690_p2[0:0] === 1'b1) ? hist_flag_V_i_fu_696_p2 : p_0351_i_fu_226);

assign p_0354_2_be_2_i_fu_783_p3 = ((tmp_75_2_i_fu_763_p2[0:0] === 1'b1) ? addr_win_val_0_V_1_fu_238 : addr_V_1_0354_2_be_s_fu_747_p3);

assign p_0354_2_be_i_fu_710_p3 = ((tmp_75_i_fu_690_p2[0:0] === 1'b1) ? addr_win_val_0_V_3_fu_242 : p_0354_i_fu_230);

assign p_177_i_i_i_fu_1625_p2 = (rev1_reg_2136 | Range1_all_zeros_1_fu_1620_p2);

assign p_179_demorgan_i_i_i_fu_1711_p2 = (tmp8_fu_1706_p2 | deleted_zeros_fu_1658_p3);

assign p_179_demorgan_i_i_no_fu_1729_p2 = (p_179_demorgan_i_i_i_fu_1711_p2 ^ 1'd1);

assign p_180_i_i_i_fu_1614_p2 = (tmp_28_i_fu_1604_p2 & Range1_all_zeros_fu_1609_p2);

assign p_3_i_fu_670_p3 = ((tmp_4_fu_664_p2[0:0] === 1'b1) ? sel_tmp3_cast_fu_656_p3 : sel_tmp_fu_618_p3);

assign p_Result_10_fu_1559_p3 = p_Val2_5_fu_1528_p3[32'd7];

assign p_Result_7_fu_1122_p3 = ireg_V_fu_1114_p1[32'd63];

assign p_Result_8_fu_1156_p1 = tmp_i1_fu_1148_p3;

assign p_Result_s_fu_1429_p3 = p_Val2_s_reg_2067[tmp_20_cast_i_fu_1426_p1];

assign p_Val2_11_0_i_i_mux_fu_1741_p3 = ((brmerge_i_i_not_i_fu_1723_p2[0:0] === 1'b1) ? p_Val2_5_fu_1528_p3 : 8'd255);

assign p_Val2_1_fu_1085_p1 = v_assign_reg_2041;

assign p_Val2_3_fu_1272_p3 = ((tmp_9_i_fu_1220_p2[0:0] === 1'b1) ? tmp_15_fu_1252_p1 : tmp_15_i_fu_1264_p3);

assign p_Val2_4_fu_1446_p2 = (p_Val2_3_reg_2109 + tmp_19_i_fu_1442_p1);

assign p_Val2_5_fu_1528_p3 = ((sel_tmp13_i_fu_1523_p2[0:0] === 1'b1) ? tmp_16_i_fu_1421_p2 : sel_tmp9_i_fu_1505_p3);

assign p_Val2_s_fu_1166_p3 = ((p_Result_7_fu_1122_p3[0:0] === 1'b1) ? man_V_1_fu_1160_p2 : p_Result_8_fu_1156_p1);

assign p_dst_data_stream_V_din = hls_lut_V_q0;

assign p_i_cast_fu_604_p3 = ((tmp_59_i_fu_584_p2[0:0] === 1'b1) ? 3'd0 : 3'd3);

assign pos1_cast_i_fu_1306_p1 = pos1_fu_1300_p2;

assign pos1_fu_1300_p2 = (12'd8 + F2_fu_1180_p2);

assign pos2_cast_i_fu_1316_p1 = pos2_fu_1310_p2;

assign pos2_fu_1310_p2 = (12'd9 + F2_fu_1180_p2);

assign qb_fu_1436_p3 = ((tmp_17_i_reg_2114[0:0] === 1'b1) ? p_Result_7_reg_2059 : p_Result_s_fu_1429_p3);

assign r_V_fu_1577_p2 = 54'd18014398509481983 >> tmp_27_i_reg_2161;

assign ret_V_1_fu_1040_p2 = ($signed(lhs_V_reg_1964) - $signed(rhs_V_fu_1036_p1));

assign ret_V_fu_684_p2 = (p_3_i_fu_670_p3 + 3'd1);

assign rev1_fu_1334_p2 = (tmp_20_fu_1326_p3 ^ 1'd1);

assign rev2_fu_1567_p2 = (tmp_22_reg_2150 ^ 1'd1);

assign rev_fu_1459_p2 = (tmp_18_fu_1451_p3 ^ 1'd1);

assign rhs_V_fu_1036_p1 = hist_out_V_q0;

assign sel_tmp12_demorgan_i_fu_1513_p2 = (tmp_7_i_reg_2090 | tmp_5_i_reg_2079);

assign sel_tmp12_i_fu_1517_p2 = (sel_tmp12_demorgan_i_fu_1513_p2 ^ 1'd1);

assign sel_tmp13_i_fu_1523_p2 = (sel_tmp12_i_fu_1517_p2 & icmp1_reg_2103);

assign sel_tmp1_fu_626_p2 = (tmp_59_i_fu_584_p2 ^ 1'd1);

assign sel_tmp1_i_fu_1471_p2 = (tmp_7_i_reg_2090 ^ 1'd1);

assign sel_tmp2_fu_632_p2 = (tmp_59_1_i_fu_589_p2 & sel_tmp1_fu_626_p2);

assign sel_tmp2_i_fu_1476_p2 = (tmp_5_i_reg_2079 & sel_tmp1_i_fu_1471_p2);

assign sel_tmp33_i_fu_1402_p2 = (tmp_26_i_not_fu_1396_p2 | tmp_20_fu_1326_p3);

assign sel_tmp34_i_fu_1408_p2 = (tmp_30_i_fu_1390_p2 & sel_tmp33_i_fu_1402_p2);

assign sel_tmp35_i_fu_1630_p3 = ((sel_tmp34_i_reg_2172[0:0] === 1'b1) ? Range1_all_ones_1_reg_2143 : rev1_reg_2136);

assign sel_tmp39_i_fu_1643_p3 = ((sel_tmp34_i_reg_2172[0:0] === 1'b1) ? Range1_all_zeros_fu_1609_p2 : p_177_i_i_i_fu_1625_p2);

assign sel_tmp3_cast_fu_656_p3 = ((sel_tmp7_fu_650_p2[0:0] === 1'b1) ? 3'd2 : 3'd1);

assign sel_tmp3_i_fu_1481_p2 = (sel_tmp2_i_fu_1476_p2 & p_Result_9_reg_2124);

assign sel_tmp41_i_fu_1678_p2 = (tmp_21_i_reg_2130 ^ 1'd1);

assign sel_tmp46_i_fu_1689_p2 = (tmp7_fu_1683_p2 & p_Result_7_reg_2059);

assign sel_tmp47_i_fu_1694_p2 = (tmp_21_i_reg_2130 & p_Result_7_reg_2059);

assign sel_tmp4_fu_857_p2 = (tmp_51_i_fu_799_p2 ^ 1'd1);

assign sel_tmp4_i_fu_1486_p3 = ((sel_tmp3_i_fu_1481_p2[0:0] === 1'b1) ? p_Val2_4_fu_1446_p2 : sel_tmp_i_fu_1465_p3);

assign sel_tmp50_i_demorgan_fu_1749_p2 = (tmp_i_i_i_i_reg_2047 & tmp_i_i_i_i_79_reg_2053);

assign sel_tmp50_i_fu_1753_p2 = (sel_tmp50_i_demorgan_fu_1749_p2 ^ 1'd1);

assign sel_tmp51_i_fu_1759_p2 = (tmp_3_i_reg_2073 & sel_tmp50_i_fu_1753_p2);

assign sel_tmp52_i_fu_1776_p3 = ((tmp_5_fu_1770_p2[0:0] === 1'b1) ? 8'd0 : p_Val2_5_fu_1528_p3);

assign sel_tmp55_demorgan_i_fu_1784_p2 = (tmp_demorgan_i_fu_1414_p2 | tmp_3_i_reg_2073);

assign sel_tmp55_i_fu_1789_p2 = (sel_tmp55_demorgan_i_fu_1784_p2 ^ 1'd1);

assign sel_tmp56_i_fu_1795_p2 = (sel_tmp55_i_fu_1789_p2 & brmerge_i_fu_1735_p2);

assign sel_tmp5_fu_863_p2 = (tmp_53_i_fu_811_p2 & sel_tmp4_fu_857_p2);

assign sel_tmp6_demorgan_fu_638_p2 = (tmp_59_i_fu_584_p2 | tmp_59_1_i_fu_589_p2);

assign sel_tmp6_fu_644_p2 = (sel_tmp6_demorgan_fu_638_p2 ^ 1'd1);

assign sel_tmp7_fu_650_p2 = (tmp_59_2_i_fu_594_p2 & sel_tmp6_fu_644_p2);

assign sel_tmp7_i_fu_1494_p2 = (p_Result_9_reg_2124 ^ 1'd1);

assign sel_tmp8_fu_877_p3 = ((tmp_51_i_fu_799_p2[0:0] === 1'b1) ? tmp_23_reg_1916 : storemerge_i_fu_833_p3);

assign sel_tmp8_i_fu_1499_p2 = (sel_tmp7_i_fu_1494_p2 & sel_tmp2_i_fu_1476_p2);

assign sel_tmp9_fu_849_p3 = ((tmp_51_i_fu_799_p2[0:0] === 1'b1) ? hist_win_val_0_V_0_fu_805_p2 : storemerge1_i_fu_841_p3);

assign sel_tmp9_i_fu_1505_p3 = ((sel_tmp8_i_fu_1499_p2[0:0] === 1'b1) ? p_Val2_4_fu_1446_p2 : sel_tmp4_i_fu_1486_p3);

assign sel_tmp_fu_618_p3 = ((tmp_3_fu_612_p2[0:0] === 1'b1) ? p_i_cast_fu_604_p3 : 3'd4);

assign sel_tmp_i_fu_1465_p3 = ((tmp_7_i_reg_2090[0:0] === 1'b1) ? tmp_13_reg_2097 : 8'd0);

assign storemerge1_i_fu_841_p3 = ((icmp_fu_827_p2[0:0] === 1'b1) ? p_0351_2_be_2_i_fu_791_p3 : hist_win_val_0_V_2_fu_738_p3);

assign storemerge_i_fu_833_p3 = ((icmp_fu_827_p2[0:0] === 1'b1) ? p_0354_2_be_2_i_fu_783_p3 : addr_win_val_0_V_2_fu_234);

assign sum_V_fu_1062_p2 = (hist_out_V_load_1_reg_2021 + sum_V_1_fu_274);

assign tmp5_fu_1547_p2 = (rev_fu_1459_p2 & not_sel_tmp28_i_fu_1541_p2);

assign tmp6_fu_1354_p2 = (rev1_fu_1334_p2 & lD_fu_1350_p1);

assign tmp7_fu_1683_p2 = (sel_tmp41_i_fu_1678_p2 & p_Result_10_fu_1559_p3);

assign tmp8_fu_1706_p2 = (sel_tmp41_i_fu_1678_p2 | p_Result_7_reg_2059);

assign tmp_10_i_fu_1242_p1 = $unsigned(F2_2_cast_i_fu_1206_p1);

assign tmp_11_fu_1144_p1 = ireg_V_fu_1114_p1[51:0];

assign tmp_11_i_fu_1246_p2 = $signed(p_Val2_s_fu_1166_p3) >>> tmp_10_i_fu_1242_p1;

assign tmp_12_fu_1418_p1 = F2_2_reg_2085[7:0];

assign tmp_13_fu_1216_p1 = p_Val2_s_fu_1166_p3[7:0];

assign tmp_14_fu_1226_p4 = {{F2_2_fu_1198_p3[11:3]}};

assign tmp_15_fu_1252_p1 = tmp_11_i_fu_1246_p2[7:0];

assign tmp_15_i_fu_1264_p3 = ((tmp_16_fu_1256_p3[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign tmp_16_fu_1256_p3 = p_Val2_1_fu_1085_p1[32'd31];

assign tmp_16_i_fu_1421_p2 = tmp_13_reg_2097 << tmp_12_fu_1418_p1;

assign tmp_17_i_fu_1280_p2 = (($signed(F2_fu_1180_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_18_fu_1451_p3 = p_Val2_4_fu_1446_p2[32'd7];

assign tmp_18_i_fu_1286_p2 = ($signed(12'd4095) + $signed(F2_fu_1180_p2));

assign tmp_19_i_fu_1442_p1 = qb_fu_1436_p3;

assign tmp_1_i_fu_1140_p1 = exp_tmp_V_fu_1130_p4;

assign tmp_20_cast_i_fu_1426_p1 = tmp_18_i_reg_2119;

assign tmp_20_fu_1326_p3 = pos1_fu_1300_p2[32'd11];

assign tmp_21_i_fu_1320_p2 = (($signed(pos1_fu_1300_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_23_i_fu_1340_p1 = $unsigned(pos1_cast_i_fu_1306_p1);

assign tmp_24_i_fu_1344_p2 = $signed(p_Val2_s_fu_1166_p3) >>> tmp_23_i_fu_1340_p1;

assign tmp_26_i_fu_1374_p2 = (($signed(pos2_fu_1310_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_26_i_not_fu_1396_p2 = (tmp_26_i_fu_1374_p2 ^ 1'd1);

assign tmp_27_i_fu_1380_p1 = $unsigned(pos2_cast_i_fu_1316_p1);

assign tmp_28_i_fu_1604_p2 = ((Range2_V_1_reg_2166 == 54'd0) ? 1'b1 : 1'b0);

assign tmp_30_i_fu_1390_p2 = ((pos2_fu_1310_p2 == 12'd54) ? 1'b1 : 1'b0);

assign tmp_31_i_fu_1672_p2 = (1'd1 ^ Range1_all_ones_2_i_fu_1666_p2);

assign tmp_36_i_fu_534_p2 = (($signed(i2_cast_i_fu_530_p1) < $signed(rows_reg_1810)) ? 1'b1 : 1'b0);

assign tmp_37_i_fu_549_p2 = (($signed(j_cast_i_fu_545_p1) < $signed(cols_reg_1816)) ? 1'b1 : 1'b0);

assign tmp_38_i_fu_973_p1 = addr_win_val_V_load_s_fu_965_p3;

assign tmp_39_i_fu_560_p1 = p_src_data_stream_V_dout;

assign tmp_3_fu_612_p2 = (tmp_59_i_fu_584_p2 | tmp_59_3_i_fu_599_p2);

assign tmp_3_i_fu_1174_p2 = ((tmp_8_fu_1118_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_44_i_fu_1025_p1 = ap_phi_mux_i6_i_phi_fu_435_p4;

assign tmp_45_i_fu_1030_p2 = ((hist_out_V_q0 == 20'd0) ? 1'b1 : 1'b0);

assign tmp_46_i_fu_1054_p1 = i6_i_reg_431_pp2_iter3_reg;

assign tmp_4_fu_664_p2 = (sel_tmp7_fu_650_p2 | sel_tmp2_fu_632_p2);

assign tmp_4_not_i_fu_1536_p2 = (icmp1_reg_2103 ^ 1'd1);

assign tmp_51_i_fu_799_p2 = ((p_3_i_fu_670_p3 == 3'd4) ? 1'b1 : 1'b0);

assign tmp_53_i_fu_811_p2 = ((p_3_i_fu_670_p3 == 3'd3) ? 1'b1 : 1'b0);

assign tmp_55_i_fu_892_p1 = addr_win_val_0_V_2_fu_234;

assign tmp_59_1_i_fu_589_p2 = ((tmp_23_reg_1916 == addr_win_val_0_V_2_fu_234) ? 1'b1 : 1'b0);

assign tmp_59_2_i_fu_594_p2 = ((tmp_23_reg_1916 == addr_win_val_0_V_3_fu_242) ? 1'b1 : 1'b0);

assign tmp_59_3_i_fu_599_p2 = ((tmp_23_reg_1916 == addr_last_V_fu_246) ? 1'b1 : 1'b0);

assign tmp_59_i_fu_584_p2 = ((tmp_23_reg_1916 == addr_win_val_0_V_1_fu_238) ? 1'b1 : 1'b0);

assign tmp_5_fu_1770_p2 = (underflow_fu_1698_p3 | tmp_9_fu_1764_p2);

assign tmp_5_i_fu_1186_p2 = (($signed(F2_fu_1180_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign tmp_6_fu_817_p4 = {{p_3_i_fu_670_p3[2:1]}};

assign tmp_6_i_fu_1192_p2 = (12'd0 - F2_fu_1180_p2);

assign tmp_73_1_i_fu_726_p2 = ((ret_V_fu_684_p2 == 3'd2) ? 1'b1 : 1'b0);

assign tmp_75_2_i_fu_763_p2 = ((p_3_i_fu_670_p3 == 3'd0) ? 1'b1 : 1'b0);

assign tmp_75_i_fu_690_p2 = ((ret_V_fu_684_p2 == 3'd3) ? 1'b1 : 1'b0);

assign tmp_7_i_fu_1210_p2 = ((exp_tmp_V_fu_1130_p4 == 11'd1075) ? 1'b1 : 1'b0);

assign tmp_8_fu_1118_p1 = ireg_V_fu_1114_p1[62:0];

assign tmp_9_fu_1764_p2 = (tmp_demorgan_i_fu_1414_p2 | sel_tmp51_i_fu_1759_p2);

assign tmp_9_i_fu_1220_p2 = ((F2_2_fu_1198_p3 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_V_1_fu_1098_p1 = p_Val2_1_fu_1085_p1[22:0];

assign tmp_V_fu_1088_p4 = {{p_Val2_1_fu_1085_p1[30:23]}};

assign tmp_demorgan_i_fu_1414_p2 = (tmp_i_i_i_i_reg_2047 & tmp_i_i_i_i_79_reg_2053);

assign tmp_i1_fu_1148_p3 = {{1'd1}, {tmp_11_fu_1144_p1}};

assign tmp_i_fu_485_p1 = i1_i_reg_387;

assign tmp_i_i_i_i_79_fu_1108_p2 = ((tmp_V_1_fu_1098_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_i_i_i_i_fu_1102_p2 = ((tmp_V_fu_1088_p4 == 8'd255) ? 1'b1 : 1'b0);

assign underflow_fu_1698_p3 = ((sel_tmp47_i_fu_1694_p2[0:0] === 1'b1) ? tmp_31_i_fu_1672_p2 : sel_tmp46_i_fu_1689_p2);

assign underflow_not_i_fu_1717_p2 = (underflow_fu_1698_p3 ^ 1'd1);

assign val_V_fu_1801_p3 = ((sel_tmp56_i_fu_1795_p2[0:0] === 1'b1) ? p_Val2_11_0_i_i_mux_fu_1741_p3 : sel_tmp52_i_fu_1776_p3);

always @ (posedge ap_clk) begin
    tmp_44_i_reg_1982[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_46_i_reg_2011[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_46_i_reg_2011_pp2_iter4_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_46_i_reg_2011_pp2_iter5_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_46_i_reg_2011_pp2_iter6_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_27_i_reg_2161[53:32] <= 22'b0000000000000000000000;
end

endmodule //Equalize
